
[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"      # Required if Vite depends on Node.js
  NPM_FLAGS = "--legacy-peer-deps" # Avoid dependency issues

# Redirects (Important for Vue Router history mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers (Optional: Set security headers)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: Netlify Edge Functions (If needed)
# [[edge_functions]]
#   path = "/*"
#   function = "your-edge-function"

